export const CATEGORIES = [
  'Analytics',
  'Artificial Intelligence',
  'Community',
  'Content Creation',
  'Crypto & Web3',
  'Customer Support',
  'Design Tools',
  'Developer Tools',
  'E-commerce',
  'Education',
  'Entertainment',
  'Fintech',
  'Games',
  'Green Tech',
  'Health & Fitness',
  'IoT & Hardware',
  'Legal',
  'Marketing',
  'Marketplace',
  'Mobile Apps',
  'News & Magazines',
  'No-Code',
  'Productivity',
  'Real Estate',
  'Recruiting & HR',
  'SaaS',
  'Sales',
  'Security',
] as const;

export type Category = (typeof CATEGORIES)[number];
