export interface MetaData {
  favicon: string;
  title: string;
  description: string;
  image?: string;
}

export interface LeaderboardItem {
  id?: string;
  rank: number;
  name: string;
  bid: number;
  url: string;
  clicks: number;
  time: string;
  upvotes?: number;
  downvotes?: number;
  net_score?: number;
  hot_score?: number;
  user_vote?: 1 | -1 | 0;
  category?: string;
  claimed_at?: string;
  favicon?: string;
  preview_image_url?: string;
  is_verified?: boolean;
  is_dofollow?: boolean;
  verified_at?: string;
}

// Seed data for `supabase/seed.sql` / local development when no database is
// configured. Live data is served from Supabase via `lib/leaderboard.ts`.
export const leaderboardItems: LeaderboardItem[] = [
  {
    rank: 1,
    name: 'outrank.so',
    bid: 12052,
    url: 'https://outrank.so',
    clicks: 0,
    time: '3 minutes ago',
  },
  {
    rank: 2,
    name: 'orynth.dev',
    bid: 12051,
    url: 'https://orynth.dev',
    clicks: 0,
    time: '8 minutes ago',
  },
  {
    rank: 3,
    name: 'trycomp.ai',
    bid: 10000,
    url: 'https://trycomp.ai',
    clicks: 0,
    time: '14 hours ago',
  },
  {
    rank: 4,
    name: 'lathire.com',
    bid: 3100,
    url: 'https://lathire.com',
    clicks: 0,
    time: '11 hours ago',
  },
  {
    rank: 5,
    name: 'mytb.ai',
    bid: 2999,
    url: 'https://mytb.ai',
    clicks: 0,
    time: '12 hours ago',
  },
  {
    rank: 6,
    name: 'joinklover.com',
    bid: 2000,
    url: 'https://joinklover.com',
    clicks: 0,
    time: '15 hours ago',
  },
  {
    rank: 7,
    name: 'peptiprices.com',
    bid: 1275,
    url: 'https://peptiprices.com',
    clicks: 0,
    time: '6 hours ago',
  },
  {
    rank: 8,
    name: 'evomarketing.co',
    bid: 1250,
    url: 'https://evomarketing.co',
    clicks: 0,
    time: '12 hours ago',
  },
  {
    rank: 9,
    name: 'fiber.so',
    bid: 1029,
    url: 'https://fiber.so',
    clicks: 0,
    time: '14 hours ago',
  },
  {
    rank: 10,
    name: 'prelint.com',
    bid: 1028,
    url: 'https://prelint.com',
    clicks: 0,
    time: '15 hours ago',
  },
  {
    rank: 11,
    name: 'neocam.app',
    bid: 1027,
    url: 'https://neocam.app',
    clicks: 0,
    time: '15 hours ago',
  },
  {
    rank: 12,
    name: 'trycodus.com',
    bid: 1026,
    url: 'https://trycodus.com',
    clicks: 0,
    time: '16 hours ago',
  },
  {
    rank: 13,
    name: 'ranked.ai',
    bid: 1025,
    url: 'https://ranked.ai',
    clicks: 0,
    time: '16 hours ago',
  },
  {
    rank: 14,
    name: 'limestonedigital.com',
    bid: 1024,
    url: 'https://limestonedigital.com',
    clicks: 0,
    time: '16 hours ago',
  },
  {
    rank: 15,
    name: 'overskill.com',
    bid: 1023,
    url: 'https://overskill.com',
    clicks: 0,
    time: '16 hours ago',
  },
  {
    rank: 16,
    name: 'startglobal.co',
    bid: 1022,
    url: 'https://startglobal.co',
    clicks: 0,
    time: '17 hours ago',
  },
  {
    rank: 17,
    name: 'capitalgurus.com',
    bid: 1021,
    url: 'https://capitalgurus.com',
    clicks: 0,
    time: '17 hours ago',
  },
  {
    rank: 18,
    name: 'fuellog.ai',
    bid: 1012,
    url: 'https://fuellog.ai',
    clicks: 0,
    time: '18 hours ago',
  },
  {
    rank: 19,
    name: 'myworkoutlogs.com',
    bid: 1007,
    url: 'https://myworkoutlogs.com',
    clicks: 0,
    time: '19 hours ago',
  },
  {
    rank: 20,
    name: 'turingo.net',
    bid: 557,
    url: 'https://turingo.net',
    clicks: 0,
    time: '1 hour ago',
  },
  { rank: 21, name: 'olvy.co', bid: 556, url: 'https://olvy.co', clicks: 0, time: '2 hours ago' },
  {
    rank: 22,
    name: 'peptidebenchmark.com',
    bid: 555,
    url: 'https://peptidebenchmark.com',
    clicks: 0,
    time: '14 hours ago',
  },
  {
    rank: 23,
    name: 'auraplusplus.com',
    bid: 501,
    url: 'https://auraplusplus.com',
    clicks: 0,
    time: '20 hours ago',
  },
  {
    rank: 24,
    name: 'reactbits.dev',
    bid: 430,
    url: 'https://reactbits.dev',
    clicks: 0,
    time: '20 hours ago',
  },
  {
    rank: 25,
    name: 'attentionfactory.com',
    bid: 421,
    url: 'https://attentionfactory.com',
    clicks: 0,
    time: '8 hours ago',
  },
  {
    rank: 26,
    name: 'post-bridge.com',
    bid: 420,
    url: 'https://post-bridge.com',
    clicks: 0,
    time: '21 hours ago',
  },
  {
    rank: 27,
    name: 'overround.pro',
    bid: 316,
    url: 'https://overround.pro',
    clicks: 0,
    time: '3 hours ago',
  },
  {
    rank: 28,
    name: 'spinhire.us',
    bid: 315,
    url: 'https://spinhire.us',
    clicks: 0,
    time: '15 hours ago',
  },
  {
    rank: 29,
    name: 'invofox.com',
    bid: 314,
    url: 'https://invofox.com',
    clicks: 0,
    time: '17 hours ago',
  },
  {
    rank: 30,
    name: 'petecodes.io',
    bid: 308,
    url: 'https://petecodes.io',
    clicks: 0,
    time: '17 hours ago',
  },
  {
    rank: 31,
    name: 'tinystartups.com',
    bid: 307,
    url: 'https://tinystartups.com',
    clicks: 0,
    time: '21 hours ago',
  },
  {
    rank: 32,
    name: 'tolt.com',
    bid: 306,
    url: 'https://tolt.com',
    clicks: 0,
    time: '22 hours ago',
  },
  {
    rank: 33,
    name: 'knoku.com',
    bid: 305,
    url: 'https://knoku.com',
    clicks: 0,
    time: '22 hours ago',
  },
  {
    rank: 34,
    name: 'prospactive.nl',
    bid: 303,
    url: 'https://prospactive.nl',
    clicks: 0,
    time: '23 hours ago',
  },
  {
    rank: 35,
    name: 'gathershot.com',
    bid: 303,
    url: 'https://gathershot.com',
    clicks: 0,
    time: '13 hours ago',
  },
  { rank: 36, name: 'shp.ee', bid: 302, url: 'https://shp.ee', clicks: 0, time: 'yesterday' },
  {
    rank: 37,
    name: 'crashino.com',
    bid: 301,
    url: 'https://crashino.com',
    clicks: 0,
    time: 'yesterday',
  },
  {
    rank: 38,
    name: 'tinkerer.club',
    bid: 300,
    url: 'https://tinkerer.club',
    clicks: 0,
    time: 'yesterday',
  },
  {
    rank: 39,
    name: 'pump.fun',
    bid: 300,
    url: 'https://pump.fun',
    clicks: 0,
    time: '4 hours ago',
  },
  {
    rank: 40,
    name: 'brian-grover',
    bid: 250,
    url: 'https://brian-grover.com',
    clicks: 0,
    time: '13 hours ago',
  },
  {
    rank: 41,
    name: 'founderstack.pro',
    bid: 203,
    url: 'https://founderstack.pro',
    clicks: 0,
    time: 'yesterday',
  },
  { rank: 42, name: 'wave.co', bid: 202, url: 'https://wave.co', clicks: 0, time: 'yesterday' },
  {
    rank: 43,
    name: 'recovery.com',
    bid: 201,
    url: 'https://recovery.com',
    clicks: 0,
    time: 'yesterday',
  },
  {
    rank: 44,
    name: 'queuebrick.com',
    bid: 200,
    url: 'https://queuebrick.com',
    clicks: 0,
    time: 'yesterday',
  },
  {
    rank: 45,
    name: 'coachparin.com',
    bid: 151,
    url: 'https://coachparin.com',
    clicks: 0,
    time: '1 hour ago',
  },
  {
    rank: 46,
    name: 'watchbid.lol',
    bid: 150,
    url: 'https://watchbid.lol',
    clicks: 0,
    time: '4 hours ago',
  },
  {
    rank: 47,
    name: 'genlook.app',
    bid: 115,
    url: 'https://genlook.app',
    clicks: 0,
    time: '1 hour ago',
  },
  {
    rank: 48,
    name: 'lowisa.dev',
    bid: 105,
    url: 'https://lowisa.dev',
    clicks: 0,
    time: '5 hours ago',
  },
  {
    rank: 49,
    name: 'shopify.com',
    bid: 105,
    url: 'https://shopify.com',
    clicks: 0,
    time: '28 minutes ago',
  },
  {
    rank: 50,
    name: 'vantaswap.com',
    bid: 101,
    url: 'https://vantaswap.com',
    clicks: 0,
    time: '11 hours ago',
  },
];
